categories:
- Statistics
description: bamcount is a tools for efficiently summarizing coverage information from a BAM file
long_description: |
    bamcount is a tool for efficiently computing coverage statistics over a DNA/RNA BAM file.
    It is aligner agnostic and counts everything over only one pass through the BAM.
    https://github.com/BenLangmead/bamcount
name: bamcount
owner: ChristoperWilks
remote_repository_url: https://github.com/ChristopherWilks/bamcount_galaxy
type: unrestricted
